package ec.com.sofka.utils.enums;

public enum EventsEnum {
    USER_CREATED,
    TRANSACTION_TYPE_CREATED,
    ACCOUNT_CREATED,
    TRANSACTION_CREATED,
    ACCOUNT_DEPOSITED,
    ACCOUNT_WITHDRAWN,
    ACCOUNT_TRANSFERRED
}